name: recaller

services:
  app:
    build:
      dockerfile: local.Dockerfile
    volumes:
        - app-node-modules:/home/node/app/node_modules
        - .:/home/node/app
    ports:
      - 3000:3000
    command: bash -c "yarn install --immutable && yarn dev"


volumes:
  app-node-modules: