name: recaller

services:
  app:
    build:
      dockerfile: local.Dockerfile
    volumes:
        - app-git-worktrees:/home/node/worktrees
        - .:/home/node/app
    ports:
      - 22222:22222
    command: bash -c "yarn install --immutable && yarn start"


volumes:
  app-git-worktrees: