name: recaller

services:
  app:
    build:
      dockerfile: local.Dockerfile
    volumes:
        - app-node-modules:/home/node/app/node_modules
        - .:/home/node/app
    ports:
      - 22222:22222
    command: bash -c "yarn start"


volumes:
  app-node-modules: